CXX=g++
RM=rm -rf
BIN_NAME=VRP

#-s  Remove all symbol table and relocation information from the executable.
INCLUDE=-I actor/ -I lib/
OPTFALGS=-O2 -march=native -mtune=native -fPIC
CPPFLAGS=-s -MD -std=c++1y -Wall -Wextra -Werror $(OPTFLAGS) $(INCLUDE) $(SECFLAGS) 
LD=-lpthread

SRCS=$(wildcard *.cpp actor/*.cpp lib/*.cpp lib/dist/*.cpp)
# notdir: get the filename from sources
OBJS_DIR=obj
OBJS=$(addprefix $(OBJS_DIR)/,$(patsubst %.cpp,%.o,$(notdir $(SRCS))))
DEPS=$(addprefix $(OBJS_DIR)/,*.d)

all: $(OBJS_DIR) $(BIN_NAME)

$(OBJS_DIR):
	mkdir $(OBJS_DIR)

$(OBJS_DIR)/%.o: %.cpp
	        $(CXX) $(CPPFLAGS) -c $< -o $@

$(OBJS_DIR)/%.o: actor/%.cpp
	        $(CXX) $(CPPFLAGS) -c $< -o $@

$(OBJS_DIR)/%.o: lib/%.cpp
	        $(CXX) $(CPPFLAGS) -c $< -o $@

$(BIN_NAME) : $(OBJS)
	$(CXX) -o $@ $^ $(LD)

debug:
	$(CXX) -g $(CPPFLAGS) -o $(BIN_NAME) $(OBJS)

.PHONY : all clean
clean:
	$(RM) $(OBJS) $(OBJS_DIR) $(DEPS)

dist-clean: clean
	$(RM) $(BIN_NAME)

# Pull-in dependencies generated by -MD
-include $(OBJS:.o=.d)
